### ISSUE TITLE
The error is as follows, how to get dino_vitbase16_pretrain.pth

### ISSUE THREAD

**Issue by gangxu822** [SarahRastegar/SelEx#4]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/nas/n/xugang/code/SelEx/methods/contrastive_training/contrastive_training.py", line 718, in <module>
    state_dict = torch.load(pretrain_path, map_location='cpu')['teacher']
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../pretrained_models/dino/dino_vitbase16_pretrain.pth

**Comment by SarahRastegar** [comment]
The error is that dino_vitbase16_pretrain.pth is not found, so please make sure it is in the desired directory. This part of the code is loading pretrained weights of the VIT so you can also use the main GCD paper by Vaze et al for this part of the code.
